const products = [
  {
    name: "Lettuce",
    description: "Fresh Lettuce",
    price: "$3.49 per head",
    unitPrice: 3.49,
    Vegan: true,
    GlutenFree: true,
    Organic: false,
    NonOrganic: true,
    image: "images/lettuce.png",
    category: "Vegetables",
  },
  {
    name: "Tomatoes",
    description: "Ripe Tomatoes",
    price: "$3.99 per lb",
    unitPrice: 3.99,
    Vegan: true,
    GlutenFree: true,
    Organic: false,
    NonOrganic: true,
    image: "images/tomato.png",
    category: "Vegetables",
  },
  {
    name: "Potatoes",
    description: "Russet Potatoes",
    price: "$2.00 per lb",
    unitPrice: 2.00,
    Vegan: true,
    GlutenFree: true,
    Organic: false,
    NonOrganic: true,
    image: "images/potato.png",
    category: "Vegetables",
  },
  {
    name: "Apples",
    description: "Fresh Green Apples",
    price: "$3.00 per lb",
    unitPrice: 3.00,
    Vegan: true,
    GlutenFree: true,
    Organic: false,
    NonOrganic: true,
    image: "images/apple.png",
    category: "Fruits",
  },
  {
    name: "Oranges",
    description: "Juicy Oranges",
    price: "$2.99 per lb",
    unitPrice: 2.99,
    Vegan: true,
    GlutenFree: true,
    Organic: false,
    NonOrganic: true,
    image: "images/orange.png",
    category: "Fruits",
  },
  {
    name: "Bananas",
    description: "Yellow Banana",
    price: "$1.75 per bunch",
    unitPrice: 1.75,
    Vegan: true,
    GlutenFree: true,
    Organic: false,
    NonOrganic: true,
    image: "images/banana.png",
    category: "Fruits",
  },
  {
    name: "Strawberries",
    description: "Fresh Strawberries",
    price: "$5.99 ea",
    unitPrice: 5.99,
    Vegan: true,
    GlutenFree: true,
    Organic: false,
    NonOrganic: true,
    image: "images/strawberries.png",
    category: "Fruits",
  },
  {
    name: "Blueberries",
    description: "Organic Blueberries Half Pint",
    price: "$5.99 ea",
    unitPrice: 5.99,
    Vegan: true,
    GlutenFree: true,
    Organic: true,
    NonOrganic: false,
    image: "images/blueberries.png",
    category: "Fruits",
  },
  {
    name: "Red Peppers",
    description: "Fresh Red Peppers",
    price: "$2.64 ea",
    unitPrice: 2.64,
    Vegan: true,
    GlutenFree: true,
    Organic: false,
    NonOrganic: true,
    image: "images/redPepper.png",
    category: "Vegetables",
  },
  {
    name: "Mushrooms",
    description: "Organic Whole Cremini Mushrooms",
    price: "$3.49 ea",
    unitPrice: 3.49,
    Vegan: true,
    GlutenFree: true,
    Organic: true,
    NonOrganic: false,
    image: "images/mushrooms.png",
    category: "Vegetables",
  },
  {
    name: "Grapes",
    description: "Green Seedless Grapes",
    price: "$4.48 ea",
    unitPrice: 4.48,
    Vegan: true,
    GlutenFree: true,
    Organic: false,
    NonOrganic: true,
    image: "images/grapes.png",
    category: "Fruits",
  },
  {
    name: "Sliced Bread",
    description: "Whole Wheat Bread",
    price: "$3.99 per loaf",
    unitPrice: 3.99,
    Vegan: true,
    GlutenFree: false,
    Organic: false,
    NonOrganic: true,
    image: "images/bread.png",
    category: "Wheat",
  },
  {
    name: "Bagel",
    description: "14 Grain Bagels",
    price: "$4.49 ea",
    unitPrice: 4.49,
    Vegan: true,
    GlutenFree: false,
    Organic: false,
    NonOrganic: true,
    image: "images/bagel.png",
    category: "Wheat",
  },
  {
    name: "Yogurt",
    description: "Yogurt With Probiotics, Vanilla Flavour",
    price: "$4.99 ea",
    unitPrice: 4.99,
    Vegan: false,
    GlutenFree: true,
    Organic: false,
    NonOrganic: true,
    image: "images/yogurt.png",
    category: "Dairy",
  },
  {
    name: "Broccoli",
    description: "Raw Broccoli",
    price: "$3.99 ea",
    unitPrice: 3.99,
    Vegan: true,
    GlutenFree: true,
    Organic: false,
    NonOrganic: true,
    image: "images/broccoli.png",
    category: "Vegetables",
  },
  {
    name: "Bread",
    description: "Gluten Free White Bread",
    price: "$5.49 ea",
    unitPrice: 5.49,
    Vegan: true,
    GlutenFree: true,
    Organic: false,
    NonOrganic: true,
    image: "images/glutenFreeBread.png",
    category: "Wheat",
  },
  {
    name: "Milk",
    description: "Organic 2% Milk",
    price: "$5.99 ea",
    unitPrice: 5.99,
    Vegan: false,
    GlutenFree: true,
    Organic: true,
    NonOrganic: false,
    image: "images/milk.png",
    category: "Dairy",
  },
  {
    name: "Cheese",
    description: "Cheddar Cheese Block",
    price: "$6.99 ea",
    unitPrice: 6.99,
    Vegan: false,
    GlutenFree: true,
    Organic: false,
    NonOrganic: true,
    image: "images/cheddar.png",
    category: "Dairy",
  },
  {
    name: "Eggs",
    description: "Free-range eggs",
    price: "$6.99 ea",
    unitPrice: 6.99,
    Vegan: false,
    GlutenFree: true,
    Organic: false,
    NonOrganic: true,
    image: "images/egg.png",
    category: "Dairy",
  },
  {
    name: "Bacon",
    description: "Original Natural Bacon",
    price: "$6.99 ea",
    unitPrice: 6.99,
    Vegan: false,
    GlutenFree: true,
    Organic: false,
    NonOrganic: true,
    image: "images/bacon.png",
    category: "Meats",
  },
  {
    name: "Vegan meat",
    description: "Beyond Burger Plant-Based",
    price: "$7.99 ea",
    unitPrice: 7.99,
    Vegan: true,
    GlutenFree: true,
    Organic: false,
    NonOrganic: true,
    image: "images/veganMeat.png",
    category: "Meats",
  },
  {
    name: "Butter",
    description: "Salted Butter",
    price: "$8.49 ea",
    unitPrice: 8.49,
    Vegan: false,
    GlutenFree: true,
    Organic: false,
    NonOrganic: true,
    image: "images/butter.png",
    category: "Dairy",
  },
  {
    name: "Beef",
    description: "Beef Stewing Cubes",
    price: "$10.78 ea",
    unitPrice: 10.78,
    Vegan: false,
    GlutenFree: true,
    Organic: false,
    NonOrganic: true,
    image: "images/beef.png",
    category: "Meats",
  },
  {
    name: "Chicken",
    description: "Boneless Chicken Breast",
    price: "$12.00 ea",
    unitPrice: 12.00,
    Vegan: false,
    GlutenFree: true,
    Organic: false,
    NonOrganic: true,
    image: "images/chicken.png",
    category: "Meats",
  }
];
