const products = [
    {
      name: "Lettuce",
      description: "Fresh lettuce",
      price: "$1.50 per head",
      unitPrice: 1.5,
      Vegan: true,
      GlutenFree: true,
      Organic: true,
      NonOrganic: false,
      image: "images/lettuce.png",
    },
    {
      name: "Bread",
      description: "Whole wheat bread",
      price: "$2 per loaf",
      unitPrice: 2,
      Vegan: true,
      GlutenFree: false,
      Organic: true,
      NonOrganic: false,
      image: "images/bread.png",
    },
    {
      name: "Tomatoes",
      description: "Ripe tomatoes",
      price: "$2 per lb",
      unitPrice: 2,
      Vegan: true,
      GlutenFree: true,
      Organic: true,
      NonOrganic: false,
      image: "images/tomato.png",
    },
    {
      name: "Potatoes",
      description: "Russet potatoes",
      price: "$2 per lb",
      unitPrice: 2,
      Vegan: false,
      GlutenFree: false,
      Organic: false,
      NonOrganic: true,
      image: "images/potato.png",
    },
    {
      name: "Apples",
      description: "Fresh green apples",
      price: "$3 per lb",
      unitPrice: 3,
      Vegan: true,
      GlutenFree: true,
      Organic: true,
      NonOrganic: false,
      image: "images/apple.png",
    },
    {
      name: "Eggs",
      description: "Free-range eggs",
      price: "$3 per dozen",
      unitPrice: 3,
      Vegan: false,
      GlutenFree: true,
      Organic: false,
      NonOrganic: true,
      image: "images/egg.png",
    },
    {
      name: "Milk",
      description: "Organic 2% milk",
      price: "$4 per gallon",
      unitPrice: 4,
      Vegan: false,
      GlutenFree: true,
      Organic: false,
      NonOrganic: true,
      image: "images/milk.png",
    },
    {
      name: "Oranges",
      description: "Juicy oranges",
      price: "$4 per lb",
      unitPrice: 4,
      Vegan: true,
      GlutenFree: true,
      Organic: true,
      NonOrganic: false,
      image: "images/orange.png",
    },
    {
      name: "Chicken",
      description: "Boneless chicken breast",
      price: "$8 per lb",
      unitPrice: 8,
      Vegan: false,
      GlutenFree: true,
      Organic: false,
      NonOrganic: true,
      image: "images/chicken.png",
    },
    {
        name: "Cheese",
        description: "Cheddar cheese block",
        price: "$10",
        unitPrice: 10,
        Vegan: false,
        GlutenFree: true,
        Organic: false,
        NonOrganic: true,
        image: "images/cheddar.png",
      },
  ];